name: 'Sha Version Warning'
version: 0.1.0
description: 'Github Action to raise a warning if an action is not being referred to by SHA'
inputs:
  action_path:
    description: "Path to action being checked."

outputs:
  warning_given:
    description: "Boolean if there warning was raised. Will be none if 'commit_and_push' was false."
    value: ${{ steps.action-warning.outputs.warning_given }}
 

runs:
  using: "composite"
  steps:
      id: action-warning
    - name: Action warning
      shell: bash
      run: |
        cd "$CURRENT_ACTION_PATH"
        CURRENT_SHA=$(git log -1 --format="%H")
        SHORT_SHA=$(git log -1 --format="%h")
        CURRENT_VERSION="${PWD##*/}"
        cd ..
        CURRENT_ACTION_NAME="${PWD##*/}"
        cd ..
        CURRENT_ACTION_USER="${PWD##*/}"
        #  No trust problems if same owner as current repo - not used
        ## if [[ "$GITHUB_REPOSITORY_OWNER" == "$CURRENT_ACTION_USER" ]]
        ## then
        ##  exit 0
        ## fi
        CA="$CURRENT_ACTION_USER/$CURRENT_ACTION_NAME"
        # if this already uses a pin no problem!
        if [[ $CURRENT_VERSION = @(CURRENT_SHA|SHORT_SHA) ]]
        then
          echo "warning_given=false" >> "$GITHUB_OUTPUT"
        else
          echo "warning_given=true" >> "$GITHUB_OUTPUT"
          echo "::warning title=Pin $CA::For security, replace: '$CA@$CURRENT_VERSION' with '$CA@$CURRENT_SHA #$CURRENT_VERSION'"
        fi
      env: 
        CURRENT_ACTION_PATH: ${{ inputs.action_path }}
